spring:
  application:
    name: babilonia-backend

  datasource:
    url: jdbc:postgresql://postgres:5432/babilonia
    username: babilonia
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/babilonia
          jwk-set-uri: http://localhost:8080/realms/babilonia/protocol/openid-connect/certs

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG