spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/babilonia
    username: babilonia
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/babilonia
          jwk-set-uri: http://localhost:8080/realms/babilonia/protocol/openid-connect/certs
